global:
  device: cuda
  batch_size: 32
  learning_rate: 0.001
  loss: cross_entropy
  eval_metrics: [accuracy, mae]

mpnn:
  hidden_dim: 64
  num_layers: 4
  run_name: mpnn-medium

graph_transformer:
  d_model: 32
  n_layers: 2
  n_heads: 1
  d_ff: 16
  run_name: gtransformer-medium

autograph_transformer:
  d_model: 32
  n_layers: 2
  n_heads: 1
  d_ff: 16
  run_name: autograph-medium

graphgps:
  d_model: 32
  n_layers: 2
  n_heads: 1
  hidden_dim: 32
  mpnn_num_layers: 2
  run_name: graphgps-medium
