global:
  device: cuda
  batch_size: 32
  learning_rate: 0.001
  max_samples_train: 500
  max_samples_valid: 200
  max_samples_test: 200

mpnn:
  hidden_dim: 128
  num_layers: 4
  run_name: mpnn-medium

graph_transformer:
  d_model: 32
  n_layers: 2
  n_heads: 1
  d_ff: 16
  run_name: gtransformer-medium

autograph_transformer:
  d_model: 32
  n_layers: 2
  n_heads: 1
  d_ff: 16
  run_name: autograph-medium

graphgps:
  d_model: 32
  n_layers: 2
  n_heads: 1
  hidden_dim: 16
  run_name: graphgps-medium
