mpnn:
  hidden_dim: 128
  num_layers: 4
  batch_size: 32
  learning_rate: 0.001
  device: cuda
  run_name: mpnn-medium

graph_transformer:
  d_model: 32
  n_layers: 2
  n_heads: 1
  d_ff: 16
  batch_size: 32
  learning_rate: 0.0001
  device: cuda
  run_name: gtransformer-medium

autograph_transformer:
  d_model: 32
  n_layers: 2
  n_heads: 1
  d_ff: 16
  batch_size: 32
  learning_rate: 0.0001
  device: cuda
  run_name: autograph-medium

graphgps:
  d_model: 32
  n_layers: 2
  hidden_dim: 16
  batch_size: 32
  learning_rate: 0.001
  device: cuda
  run_name: graphgps-medium
